### ISSUE TITLE
`Card#e_factor`

### ISSUE THREAD

**Issue by w1zeman1p** [tpizzle/Devour#3]
Seems like e_factor is going to be a function of correct answers right? In that case, i wouldn't store it in the DB, but have it be a function of the number of correct answers from the current user.

**Comment by w1zeman1p** [comment]
In this case you might also need to keep track of all previous answers from a user. so in addition to keeping the correct answer in the card keeping all answer submissions in some table. Maybe called AnswerAttempt or something.

**Comment by tpizzle** [comment]
Created a Response Model, which collects all data concerning current e-factor, number of repetitions(equivalent to where you are on the x-axis of the forgetting curve), last time you passed the card, and length of time until your next quiz on the card.

**Comment by tpizzle** [comment]
Also, the e-factor is updated each time a response is saved to the database.
